### ISSUE TITLE
Allow customization of CSS classes

### ISSUE THREAD

**Issue by Spone** [jimmynotjim/scrollnav#100]
Hi,

thanks for this library. We plan on using it in an upcoming project. We chose not to follow BEM conventions for naming our classes, and we would like to be able to customize the CSS classes added by scrollnav.

It could be a `cssClasses` option that would accept an object. This would be similar to the instantsearch.js implementation: https://www.algolia.com/doc/api-reference/widgets/search-box/js/?language=javascript#widget-param-cssclasses

What do you think?

**Comment by jimmynotjim** [comment]
That sounds really nice on the surface but my main concern would be the complexity added because all the classes are auto-generated from the base class. A good example is [the `createList` function](https://github.com/jimmynotjim/scrollnav/blob/master/src/util/createList.js) which is used to generate both the section and sub-section lists.

If you're willing to rework things in a way __that doesn't add a lot of overhead__ I'd be open to a Pull Request.

**Comment by grebaldi** [comment]
How about customizing the base class? I think the major concern here is collisions of multiple instances of scrollnav. Allowing a custom base class would imho solve that problem sufficiently.

**Comment by jimmynotjim** [comment]
That could work. I used to allow for customizing the base class but removed it in v3 because the custom options were getting out of hand. @grebaldi want to submit a PR?

**Comment by grebaldi** [comment]
I'll have a look into it @jimmynotjim

**Comment by jimmynotjim** [comment]
Closing due to lack of time and little interest in this request. If you would like to work on this feature feel free to create a PR and send it my way to look over.
