### ISSUE TITLE
Wrong active item using reset.css

### ISSUE THREAD

**Issue by jdmoliner** [jimmynotjim/scrollNav#64]
Hi,

I use 'reset.css', then a 0 margin is applied to 'h2' and 'p'. Also I have a decoration below H2 called 'dotted-5'. Under these conditions I get wrong active item.

I made this example:

http://jsfiddle.net/kurtko/65je5n9v/

Thanks

**Comment by jimmynotjim** [comment]
@jdmoliner really sorry I didn't see this. I don't think this is an issue with `reset.css` because I've used that as well and it should calculate the exact positioning of the `<section>` that it wraps each chunk in. I think it actually looks like another bug that I thought I [had fixed already](https://github.com/jimmynotjim/scrollNav/pull/51), but I'll have to play with it this weekend to be sure.

**Comment by jdmoliner** [comment]
You can see in my example if you remove the next line works fine:

`p , h2 {margin:0;padding:0}`

**Comment by jimmynotjim** [comment]
Re-reviewing this and your jsfiddle seems to highlight the correct section. Luckily, the entire plugin is being rewritten to avoid inserting `section`s to the main content and should resolve any of these issues. Closing in favor of tracking in #86
