### ISSUE TITLE
Text outside of DOM Element is Displaced

### ISSUE THREAD

**Issue by JoshuaLewis** [jimmynotjim/scrollNav#73]
I found an interesting glitch with the plugin, when text is within a paragraph tag it displays as it should. However if text is not wrapped with a tag, it gets displaced.

My current configuration is:

```
$('.article-text').scrollNav({
                    sections: 'h2',
                    subSections: false,
                    sectionElem: 'section',
                    showHeadline: false,
                    headlineText: 'Table of Contents',
                    showTopLink: true,
                    topLinkText: 'Overview',
                    fixedMargin: 0,
                    scrollOffset: 44,
                    animated: true,
                    speed: 500,
                    insertTarget: this.body,
                    insertLocation: 'appendTo',
                    arrowKeys: false,
                    scrollToHash: false
});
```

I tried playing around with it to see if I could fix it. No luck. If I had to guess it probably has to do with line 62-83:

```
find_sections: function($el) {
      // Find the html for each section

      var target_elems = S.settings.sections;
      var raw_html = [];

      if (S.settings.showTopLink) {
        var $firstElem = $el.children().first();

        if ( !$firstElem.is(target_elems) ) {
          raw_html.push( $firstElem.nextUntil(target_elems).andSelf() );
        }
      }

      $el.find(target_elems).each(function() {
        raw_html.push( $(this).nextUntil(target_elems).andSelf() );
      });

      S.sections = {
        raw: raw_html
      };
    }
```

I'm not very experienced with Jquery, hence why I don't know how to also grab raw text to be inserted as well.

**Comment by jimmynotjim** [comment]
Interesting. I'm guessing it's a shortcoming of how jQuery collects everything with `nextUntil()`. I can't think of a solution offhand, but I'll try and look into it as soon as I have some time. This might be something that waits till I have time to refactor this into a native JS plugin instead of being dependent on jQuery.

**Comment by JoshuaLewis** [comment]
I'm curious why the plugin re-inserts content into sections instead of simply putting in <a name="toc-name"></a> for each header? Was it easier for the highlighter to detect sections with the re-insert section method?

As for native JS, the idea sounds fun. But would that make the plugin much heavier? 15KB of code is fine, but once it starts going over 100KB I start to get a little worried. ;-)

**Comment by jimmynotjim** [comment]
Because in order to track what's in view, you need a container. The first version of the plugin did what you suggest, but it was extremely difficult to correct guess what section the user was looking at. As far as code size, if you're loading all of jQuery, you're already bloated. I've found going native reduces my page load significantly.

**Comment by JoshuaLewis** [comment]
My personal website is using a different TOC system which does not require wrapping sections in DIV's as seen here: http://joshlewis.us/going-for-the-gusto (it's using jQuery)

The JS for the TOC is 2.4kb. Due to the methods being used it is not being affected by new loading images in terms of highlighting.

According to ScrollNav's frontpage source code it is loading the following file:
`http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js`

This makes me a little confused when you say "As far as code size, if you're loading all of jQuery, you're already bloated. I've found going native reduces my page load significantly." Are you talking about using only JavaScript?

**Comment by jimmynotjim** [comment]
@JoshuaLewis Oof, so sorry for missing this question, I've not been able to give this project much attention in the last two years since it's no longer a part of my daily job. I hope you understand.

What I meant was that if you are loading the entire jQuery library, there's already a lot of page bloat. I'd like to reduce the requirement to include jQuery by using just native JS for the plugin. I'd still have a jQuery option for those that wanted to use it, but it would reduce the requirement to use jQuery for those that don't want to. 

As far as when this re-write will happen, I'm not sure, I don't see me having serious time to dedicate to it any time soon, but I'm still hopeful.

**Comment by JoshuaLewis** [comment]
Thanks for getting back to me Jim. Here's a potential solution to getting text nodes:
http://stackoverflow.com/questions/298750/how-do-i-select-text-nodes-with-jquery

The issue however is figuring out the proper ordering of the text nodes to be aligned with their neighboring DOM elements. With a different TOC plugin was able to get it to load without wrapping objects as seen here: https://daringdreams.com/going-for-the-gusto

Here's the TOC plugin I used: https://github.com/markserbol/tocible

**Comment by jimmynotjim** [comment]
Wanted to let you know that I'm working on a new version that if all goes well, will not be modifying the page content other than inserting the ToC and updating the headings to include IDs and links. I appreciate all your feedback and apologize for not having the time to work on this project for so long. For more details, check out #86. 

I'm going to close this issue because I've yet to find a fix for this bug in the current version, but I'd definitely love feedback in #86 if you have any.
