### ISSUE TITLE
Configurable active class

### ISSUE THREAD

**Issue by wujekbogdan** [jimmynotjim/scrollNav#76]
It's great that scrollNav's HTML is built based on a great BEM methodology. But it would be even greater if it followed all BEM rules.  By default, a list item has a `scroll-nav__item` class, so according to BEM rules, an active element should have a modifier, so an active list item should have `scroll-nav__item scroll-nav__item--active` classes. 

I know that this change would cause backwards compatibility issues, so I suggest adding an another configuration parameter: `activeClass`.

The same applies to other modifiers. I would replace `in-view` with `scroll-nav__item--in-view`

**Comment by jimmynotjim** [comment]
I like this idea. Instead of adding yet another config param, I'd rather release a breaking change. I'm hoping to set aside some time at some point to rewrite the entire plugin and remove the jQuery requirement. I just haven't found that time due to other obligations. Thanks for the suggestion. I'll keep this open so I don't lose track of it.

**Comment by pixelbandito** [comment]
What if you added an additional BEM-style active class without removing the current one? See my PR for reference. It could be a softer pathway to migration, and maybe add a boolean config for 'includeLegacyClasses' that could be deprecated at a later date.

**Comment by jimmynotjim** [comment]
@pixelbandito mmm, I like this idea. Thanks, I'll get this tested tonight and push a release out.

**Comment by jimmynotjim** [comment]
PR is merged and changes are deployed as 2.7.3. Thanks again.
