### ISSUE TITLE
Are wrappers really needed?

### ISSUE THREAD

**Issue by wujekbogdan** [jimmynotjim/scrollNav#78]
I see that each section is wrapped in `scroll-nav__section` element. Is it really needed? IMO it could be implemented in a different way.

I can see at least 2 scenarios:

1. ID's could be added directly to header elements. ID's could be generated based on a header text. I know that it could cause duplicated IDs. But this problem is easy to solve. In case of duplicated IDs a suffix could be added (#duplicated-header-1, #duplicated-header-2, and so on)
2. The plugin could rely on ID's that already exist in the HTML. Of source,  It would mean that users have to deal with ID's on their own, but it's OK. It could be an optional feature. The first solution might be a default one, the second solution might be an advanced mode.

**Comment by jimmynotjim** [comment]
The early versions of the plugin used your example from #1. The issue was knowing when a section came into view for the `in-view` class. 

I've tried a few solutions but could never quite get them working as well. Even with the current solution, it's hard to show the state of the bottom most section, because even if an item is on the screen, it might be the very last thing, and you can't really tell user intent just by scroll action alone.

If you have a solution, I'm very open to PRs and have even been looking for someone to become a maintainer and help push the project forward.

**Comment by wujekbogdan** [comment]
@jimmynotjim
I see. Actually, I had a similar issue when I tried to write a similar plugin once :)

**Comment by jimmynotjim** [comment]
I've been thinking about this the last few months and think I have a solution. Including it in the overhaul I'm planning for v3, see #86 for more details.

**Comment by jimmynotjim** [comment]
Turns out wrappers aren't needed 🎉It took a bit of head scratching but I was able to come up with a set of conditions that works really well. https://codepen.io/jimmynotjim/pen/vRyJPJ?editors=0010 The red highlight is a debugger to show where the boundary starts and stops. The best part is if there is no heading within the boundary it defaults to the last heading meaning there's no longer an issue of headings flashing on and off as well. There's still a possibility of never highlighting headings at the bottom of a page that can't be scrolled into the boundaries, but that was an issue even with the wrappers. Keep your eye out for a release on v3 in a few weeks.
